auth/urls.py
from django.urls import path
from auth.views import login_user, register_user, logout_user

app_name = "auth"

urlpatterns = [
    path("login", login_user, name="login"),
    path("register", register_user, name="register"),
    path("logout", logout_user, name="logout"),
]

berita/urls.py
from django.urls import path
from berita.views import show_landing_news, show_news, show_json, show_json_comment, add_comment, show_url, show_profile, show_all_comments, addComment_flutter

app_name='berita'

urlpatterns = [
    path('', show_landing_news, name='show_landing_news'), 
    path('news_page/<int:id>', show_news, name='headline_news'), 
    path('json/', show_json, name='json'), 
    path('news_page/json_comment/<int:id>', show_json_comment, name='json_comment'), 
    path('news_page/add_comment/<int:id>', add_comment, name='add_comment'), 
    path('show_url', show_url, name='show_url'), 
    path('show_profile', show_profile, name='show_profile'), 
    path('show_comment', show_all_comments, name='show_all_comments'),
    path('addComment_flutter/', addComment_flutter, name='addComment_flutter'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("penjualan/", include("penjualan.urls")),
    path("landing/", include("landing.urls")),
    path("berita/", include("berita.urls")),
    path("profile-umkm/", include("profileUMKM.urls")),
    path("reviewUMKM/", include("reviewUMKM.urls")),
    path("authentication/", include("authentication.urls")),
]

berita/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User 
from landing.models import Profile

# Create your models here.

class NewsModel(models.Model):
    news_title = models.CharField(max_length=255)
    news_body = models.TextField(blank=True)
    news_source = models.URLField(max_length=500)
    news_image = models.URLField(max_length=500)
    news_published = models.CharField(max_length=255)
    
class CommentModel(models.Model):
    comments_substance = models.TextField(blank=True)
    user = models.ForeignKey(Profile, related_name="profile", on_delete=models.CASCADE)
    news = models.ForeignKey(NewsModel, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)

berita/forms.py
from django.forms import ModelForm
from berita.models import CommentModel

class CommentForm(ModelForm):
    class Meta:
        model = CommentModel
        fields = ['comments_substance',]

berita/views.py
from datetime import datetime
from time import timezone
from django.shortcuts import render, get_object_or_404
from berita.models import NewsModel
from berita.models import CommentModel
from landing.models import Profile
from django.http import HttpResponse
import datetime
from django.core import serializers
from django.http import Http404
from django.contrib.auth.decorators import login_required
from landing.models import Profile
from django.contrib.auth import authenticate
from berita.forms import CommentForm
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.

def show_landing_news(request):
    
    news = NewsModel.objects.all()
    context = {
        'berita': news, 
    }
    return render(request, 'news_landing_page.html', context)

def show_news(request, id):
    profile = None
    berita = NewsModel.objects.filter(pk=id)
    comments = CommentModel.objects.filter(news__pk=id).order_by('date_added').values()
    if request.user.is_authenticated:
        profile = get_object_or_404(Profile, user=request.user)
    context = {
        'news': berita, 
        'comments': comments, 
        'user':profile,
    }
    return render(request, 'news_page.html', context)

def show_json(request):
    data = NewsModel.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_comment(request, id):
    data = CommentModel.objects.filter(news__pk=id)
    return HttpResponse(serializers.serialize("json", data, use_natural_foreign_keys=True), content_type="application/json")

def show_profile(request):
    data_profile = Profile.objects.all()
    return HttpResponse(serializers.serialize("json", data_profile), content_type="application/json")

def show_all_comments(request):
    data = CommentModel.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/landing/login/')
def add_comment(request, id):
    print(id)
    if (request.method == 'POST'):
        comments_substance = request.POST.get('comments_substance')
        try:
            news = NewsModel.objects.get(pk=id)
        except NewsModel.DoesNotExist:
            raise Http404("No Model matches")

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
        
        # if profile.roles == 'K':
        new_comment = CommentModel.objects.create(
            comments_substance=comments_substance, 
            user = profile, 
            news = news, 
            date_added = datetime.datetime.now(), 
        )

        new_comment.save()
        return HttpResponse("")
    return render (request, "news_page.html")

def show_url(request):
    return request.path_info

@csrf_exempt
def addComment_flutter(request):
    try: 
        comments_substance = request.POST.get("comments_substance")
        
        try:
            profile = Profile.objects.get(user=request.user)
            news = NewsModel.objects.get(pk=int(request.POST.get('news_index')))
        except NewsModel.DoesNotExist:
            return JsonResponse({"message" : "No News"})
        
        new_comment = CommentModel(
            comments_substance=comments_substance, 
            user = profile, 
            news = news, 
            date_added = datetime.datetime.now(), 
        )

        new_comment.save()

        response_data = {
            'comments_substance': comments_substance, 
            'user' : profile,
            'news' : news, 
            'date_added' : datetime.datetime.now(), 
        }
        return JsonResponse(response_data)
    except:
        return JsonResponse({"message" : "Failed!"})

berita/templates/news_landing_page.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/news_landing.css' %}"/>
    <!-- <script defer src="{% static 'js/news_landing.js' %}"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    
    <script>
        function showHeadline() {
            $.get("{% url 'berita:json'%}", function(data){

                for (var i = 0; i < 1; i++) {
                    var news_title = document.getElementById("first-headline"); 
                    var news_body = document.getElementById("newsbody1"); 
                    var news_image = document.getElementById("headline1-bg"); 
                    var id_berita = data[i].pk
                    
                    news_image.style.backgroundImage = "url(" + data[i].fields.news_image + ")";    
                    
                    news_title.innerHTML = data[i].fields.news_title; 
                    news_title.setAttribute("href", "news_page/".concat(id_berita));
                    news_body.innerHTML = data[i].fields.news_body; 
                     
                }

                for (var j = 1; j < 2; j++) {
                    var news_title = document.getElementById("second-headline"); 
                    var news_body = document.getElementById("newsbody2"); 
                    var news_image = document.getElementById("headline2-bg"); 
                    var id_berita = data[i].pk
                    news_title.setAttribute("href", "news_page/".concat(id_berita));

                    news_image.style.backgroundImage = "url(" + data[j].fields.news_image + ")";    
                    

                    news_title.innerHTML = data[j].fields.news_title; 
                    news_body.innerHTML = data[j].fields.news_body; 
                }

                for (var k = 2; k < 3; k++) {
                    var news_title = document.getElementById("third-headline"); 
                    var news_body = document.getElementById("newsbody3"); 
                    var news_image = document.getElementById("headline3-bg"); 
                    var id_berita = data[k].pk
                    news_title.setAttribute("href", "news_page/".concat(id_berita));
                    
                    news_image.style.backgroundImage = "url(" + data[k].fields.news_image + ")";    
                
                    news_title.innerHTML = data[k].fields.news_title; 
                    

                    news_body.innerHTML = data[k].fields.news_body; 
                }
            })
        }

        $(document).ready(function(){
            showHeadline(); 
        })

        function showNewsCard() {
            $.get("{% url 'berita:json'%}",function(data){
                
                    var newsCard = document.getElementById("card-news"); 
                    newsCard.innerHTML = ""
                    let htmlstring = ``
                    let href = "news_page/"

                    
                    for (var i = 3; i < data.length -5; i++) {
                    var id_berita = data[i].pk
                    
                    htmlstring += 
                    
                    `
                    

                        <div class="card h-100 shadow p-3 mb-5 bg-body rounded border-0" id="news-card">
                            <img class="card-img-top rounded-0" src="${data[i].fields.news_image}" alt="news image">
                            <div class="card-body" >
                                <a class="card-title" id="newsCardTitle" href=${href.concat(id_berita)}>${data[i].fields.news_title}</a>
                                <p class="card-text" id="card-news-body">${data[i].fields.news_body}</p>
                            </div>
                        </div>
                    `
                    
                    }

                    newsCard.innerHTML = htmlstring
                    let str = document.getElementById("card-news-body").innerHTML; 
                    let res = str.replace(/\\n/g, '<br> <br>');
                    document.getElementById("card-news-body").innerHTML = res;
            })
        }

        $(document).ready(function(){
            showNewsCard(); 
        })

        function showSideNews(){
            $.get("{% url 'berita:json'%}", function(data){
                var sideNews = document.getElementById("side-news"); 
                sideNews.innerHTML = ""
                let htmlstring = ``
                let href = "news_page/"

                for (var i = data.length - 5; i < data.length; i++) {
                    var id_berita = data[i].pk
                    
                    htmlstring += 
                    
                    `
                        <div class='container2' >
                            <div id="side-news">
                                <a  href=${href.concat(id_berita)}>${data[i].fields.news_title}</a>
                                <div id="published-date">'${data[i].fields.news_published}</div>
                            </div>
                        </div>
                        
                    `
                    }
                    sideNews.innerHTML = htmlstring
            })
        }

        $(document).ready(function(){
            showSideNews(); 
        })


    </script>
{% endblock meta %}


{% block content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
   
    <div id="main-div" class="container-fluid">

        <div class="container-fluid" id="main-div2">
                
            <div id="newsCarousel" class="carousel slide" data-ride="carousel"  >
                <ol class="carousel-indicators">
                    <li data-target="#newsCarousel" data-bs-slide-to="0" class="active"></li>
                    <li data-target="#newsCarousel" data-bs-slide-to="1"></li>
                    <li data-target="#newsCarousel" data-bs-slide-to="2"></li>
                    
                </ol>
                
                <div class="carousel-inner" >
                        <div class="carousel-item active" id="headline1"  >
                            <div id="headline1-bg" class="overlay-image" ></div>
                            <div class="container-headline1">
                                <a id="first-headline" class="headline-title"></a>
                                <br>
                                <span id="newsbody1" class="d-inline-block text-truncate" ></span>
                            </div>
                        </div>

                    <div class="carousel-item">
                        <div id="headline2-bg" class="overlay-image" ></div>
                        <div class="container-headline2">
                            <a id="second-headline" class="headline-title"></a>
                            <br>
                            <span id="newsbody2" class="d-inline-block text-truncate" ></span>
                        </div>
                    </div>
                    
                    <div class="carousel-item">
                        <div id="headline3-bg" class="overlay-image" ></div>
                        <div class="container-headline3">
                            <a id="third-headline" lass="headline-title"></a>
                            <br>
                            <span id="newsbody3" class="d-inline-block text-truncate" ></span>
                        </div>
                    </div>
                    
                    <a href="#newsCarousel" class="carousel-control-prev" role="button" data-bs-slide="prev">
                        <span class="visually-hidden">Previous</span>
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </a>

                    <a href="#newsCarousel" class="carousel-control-next" role="button" data-bs-slide="next">
                        <span class="visually-hidden">Next</span>
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    <h5  id="landing-title">Berita UMKM</h5>
</div>

<div class="container">
    <div class="row ">
      <div class="col-sm-8">
        <div class="p-2" id="latest-news">
            <h5 class="news-section">Latest News</h5>
            <hr>
            <div class="d-flex flex-start justify-content-around"  id ="card-news">
                <div class="p-2" ></div>
            </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="p-2" id="news-today">
            <h5 class="news-section">News Today</h5>
            <hr>
            <div class="row row-cols-1" id="side-news">
                <div class='container2' >
                </div>
        </div>
        </div>
    </div>
</div>
</div>



{% endblock content %}
        
   

berita/templates/news_page.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<!-- <style>
    .card{
        margin-left: 50px;
    }
    #news-content{
        /* From https://css.glass */
        background: rgba(255, 255, 255, 0.2);
        border-radius: 16px;
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        backdrop-filter: blur(5px);
        -webkit-backdrop-filter: blur(5px);
        border: 1px solid rgba(255, 255, 255, 0.3);
        width: 1000px;
        margin-top: 100px;
    }
    img{
        margin-bottom: 25px; margin-top: 25px; display: block;
        margin-left: auto; margin-right: auto; max-height: 400px;
    }
    #news-title{
        text-align: center; margin-top: 20px;
    }
    #news-source{
        text-align: center;
    }
    #news-body{
        text-align: justify; word-break: break-words; font-size: large;
    }
    .sticky-bottom{
        margin-top: 20px; margin-left: auto; margin-right: auto; margin-bottom: 30px;
    }
    h2{
        margin-left: 50px;
    }
    #button-add-comment{
        margin-bottom: 15px; 
        border-radius: 50%; 
        height: 40px; 
        width: 40px; 
        background-color: rgba(78, 108, 80, 1); 
        font-size: 24px; 
        border: 0; 
        padding: 0; 
        margin-right: 50px;
    }
    #comments-substance{
        margin-bottom: 10px; margin-top: 10px; 
    } 
    #comment-div{
       margin-left: 50px; margin-right: 50px;
    }
    #head-comment{
        margin-left: 50px; line-height: 0em;
    }
    #comment-body{
        margin-left: 50px; 
    }
    hr{
        margin-bottom: 20px; opacity: 20%;
    }
</style> -->
    <meta charset="utf-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/news_page.css' %}"/>

    <script>

        var currentURL = window.location.pathname 
        let news_id = currentURL.match(/(?<=news_page\/)\d+/); 

        let profile_id = ``
        var user_comment = ``
        
        function addComment(){
            
            $.get("json_comment/"+news_id, function(data){
                $.get("{% url 'berita:show_profile' %}", function(data_profile){
                    document.getElementById("comments").innerHTML = ""
                    let htmlstring = ``
                    for (var i = 0; i < data.length; i++) {

                        
                        console.log(data);
                        
                        htmlstring += 
                        `
                        <p  id="head-comment"> <b>${data[i].fields.user}</b> | <small>${data[i].fields.date_added}</small></p>
                        <p id="comment-body">${data[i].fields.comments_substance}</p>
                        <hr >
                        `
                    }   document.getElementById("comments").innerHTML += htmlstring;
                })
            })
        }
        $(document).ready(function(){
            addComment(); 
        })

    
        $(document).on('submit', '#addComment', function(e){
            
            addComment();
            addComment();
            e.preventDefault(); 
            $.ajax({
                type:"POST",
                url:"add_comment/" + news_id,
                data:{
                    comments_substance: $("#comments_substance").val(), 
                    csrfmiddlewaretoken:'{{ csrf_token }}',
                }, 
                dataType:'json', 
                success: addComment(), 
                
            })
            addComment();
            addComment();  
        })


    </script>

{% endblock meta %}
    
{% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
    
        <div class="container-md"id="news-content">
            {% for berita in news %}
                <h1  id="news-title">{{berita.news_title}}</h1>
                <img src={{berita.news_image}} alt="news-image" >
                <p  id="news_source"><small>{{berita.news_source}}</small></p>
                <hr>
               <p id="news-body">{{berita.news_body}}</p>
            {% endfor %}
         
        </div>
    <div class="sticky-bottom" >
            <h2 >Comments</h2>
        </div>

    <div  id="comment-div">
        <!-- <p>{{user}}</p> -->
            <div class="position-relative">
                
                <div id="comments">
                    {% if not comments.all %} 
                        No Comments Yet
                    {% else %}

                    {% endif %}
                </div>

                
                
                
                {% if user.roles == "K" %}
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary position-absolute bottom-0 end-0" data-bs-toggle="modal" data-bs-target="#commentModal" id="button-add-comment">
                    +
                </button>
                {% endif %}
                
                <!-- Modal -->
                <div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="commentModalLabel">Write Your Comment</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            
                            <form id="addComment" method="POST">
                               {% csrf_token %}
                                <div class="modal-body">
                                    <textarea id="comments_substance" class="form-control" aria-label="With textarea" rows="2" cols="50" placeholder="Comment Here" ></textarea>
                                </div>
                                
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Send Comment</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>  
            
    </div>

    <script>
        let str = document.getElementById("news-body").innerHTML; 
        let res = str.replace(/\\n/g, '<br> <br>');
        document.getElementById("news-body").innerHTML = res;
    </script>

        


{% endblock content %}