auth/urls.py
from django.urls import path
from auth.views import login_user, register_user, logout_user

app_name = "auth"

urlpatterns = [
    path("login", login_user, name="login"),
    path("register", register_user, name="register"),
    path("logout", logout_user, name="logout"),
]

landing/urls.py
from django.urls import path
from landing.views import *

app_name = 'landing'

urlpatterns = [
    path('', index, name='index'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json', show_json, name='show_json'),
    path('profile/', profile, name='profile'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("penjualan/", include("penjualan.urls")),
    path("landing/", include("landing.urls")),
    path("berita/", include("berita.urls")),
    path("profile-umkm/", include("profileUMKM.urls")),
    path("reviewUMKM/", include("reviewUMKM.urls")),
    path("authentication/", include("authentication.urls")),
]

landing/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    roles = models.CharField(max_length=1)

    def konsumen(self):
        if self.roles == 'K':
            return True
        return False

    def investor(self):
        if self.roles == 'I':
            return True
        return False

    def pemilik(self):
        if self.roles == 'P':
            return True
        return False

    def __str__(self):
        return self.user.username

    def natural_key(self):
        return self.name

landing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUp(UserCreationForm):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    ROLES_CHOICES = [('K', 'Konsumen'),
                     ('I', 'Investor'),
                     ('P', 'Pemilik')]
    roles = forms.ChoiceField(
        label="Roles",
        required=True,
        choices=ROLES_CHOICES,
        widget=forms.RadioSelect()
    )

    class Meta:
        model = User
        fields = ['username', 'name', 'email', 'roles', 'password1']

    def save(self, commit=True):
        user = super(SignUp, self).save(commit=False)
        user.name = self.cleaned_data["name"]
        user.email = self.cleaned_data["email"]
        user.roles = self.cleaned_data["roles"]

        if commit:
            user.save()

        return user

landing/views.py
from cgitb import reset
import datetime
from .models import Profile
from .forms import SignUp
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.contrib.auth.backends import UserModel

# Create your views here.


def index(request):
    return render(request, 'home.html')


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(
        reverse("landing:login"))
    response.delete_cookie('last_login')
    return response


def register(request):
    form = SignUp()

    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            pengguna = form.save()
            Profile.objects.create(
                user=pengguna, name=pengguna.name, email=pengguna.email, roles=pengguna.roles)
            messages.success(request, 'Akun berhasil dibuat!')
            return redirect("landing:login")

    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(
                reverse("landing:index"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def show_roles(request):
    user = ""
    if request.user.is_authenticated:
        user = Profile.objects.filter(user=request.user)
    context = {
        'user': user,
        "is_authenticated": request.user.is_authenticated,
    }
    return render(request, "base.html", context)


@login_required(login_url='/landing/login/')
def show_json(request):
    user = request.user
    data = Profile.objects.filter(user=user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


@login_required(login_url='/landing/login/')
def profile(request):
    user = request.user
    data = Profile.objects.filter(user=user)
    return render(request, 'profile.html', {'data': data})

landing/templates/home.html
{% extends 'base.html' %} 

{% block meta %}
<title>Home</title>
<style>
  .p-2{
    min-height: 50%;
  }
img{
  position: relative;
  max-width: 40%;
  max-height: min-content;
}

</style>
{% endblock meta %} 


{% block content %}
<body style="background-color: grey;">
  
  <div class="container-fluid" style="background-color: white; padding-bottom: 5%; padding-top: 50px;"> 
    <div class="d-flex flex-row align-items-start" style="flex-wrap: wrap; white-space: nowrap;">
      <div class="p-2" style="margin-left:0px; left: 0px;">
      <p></p>
    </div>
      <div class="p-2" style="margin-top: 50px; ">
        <h1 style="text-align: start;">GoUMKM</h1>
        <hr>
        <h5 style="text-align: start;">Boost Your UMKM Through GoUMKM</h5>
        <img src="https://img.freepik.com/free-vector/we-are-open-concept-illustration_114360-9780.jpg?w=826&t=st=1667405961~exp=1667406561~hmac=8e75c9d77f0aab685fd8a10f860e5579170dec54877a09e862542451bcb04535">
      </div>
    </div>  
  </div>

  <p style="margin-left: 20px;"><b><small>Contributors: Ihza Dafa Maulidan, Ahmadhi Prananta Hastiputra, Shafa Aleyda Tsabitah, Rafinal Haryokusumo Taloputra, Sania Rizqi Maharani</small></b></p>
</body>
{% endblock content %}

landing/templates/home2.html
{% extends 'base.html' %}  
{% block meta %}
{% endblock meta %} 

{% block content %}

landing/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
   
<link href="{% static 'style1.css' %}" rel="stylesheet">

<body class="text-center">

    <form class="form-signin w-100 m-auto" method="POST" action="">
        {% csrf_token %}
        <h1 class="h3 mb-4 fw-normal">Log in</h1>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger">
                        <strong>{{ message|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-floating">
            <input type="text" name="username" placeholder="Username" class="form-control">
            <label for="floatingInput">Username</label>
        </div>
        <br>
        <div class="form-floating">
            <input type="password" name="password" placeholder="Password" class="form-control">
            <label for="floatingPassword">Password</label>
        </div>

        <div class="mb-3">
            <label>
                Don't have an account? <a href="{% url 'landing:register' %}">Buat Akun</a>
            </label>
        </div>

        <input class="w-100 btn btn-lg btn-primary" type="submit" value="Login"></td>

    </form>
</body>

{% endblock content %}

landing/templates/profile.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Profile</title>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
{% endblock meta %} {% block content %}
<style>
  body {
    background-color: #f9f9fa;
  }

  main {
  display: flex;
  align-items: center;
  padding-top: 200px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

  .padding {
    padding: 3rem !important;
  }

  .user-card-full {
    overflow: hidden;
  }

  .card {
    border-radius: 5px;
    -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
    box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
    border: none;
    margin-bottom: 30px;
  }

  .m-r-0 {
    margin-right: 0px;
  }

  .m-l-0 {
    margin-left: 0px;
  }

  .user-card-full .user-profile {
    border-radius: 5px 0 0 5px;
  }

  .bg-c-lite-green {
    background: -webkit-gradient(
      linear,
      left top,
      right top,
      from(#f29263),
      to(#ee5a6f)
    );
    background: linear-gradient(to right, #ee5a6f, #f29263);
  }

  .user-profile {
    padding: 20px 0;
  }

  .card-block {
    padding: 1.25rem;
  }

  .m-b-25 {
    margin-bottom: 25px;
  }

  .img-radius {
    border-radius: 5px;
  }

  h6 {
    font-size: 14px;
  }

  .card .card-block p {
    line-height: 25px;
  }

  @media only screen and (min-width: 1400px) {
    p {
      font-size: 14px;
    }
  }

  .card-block {
    padding: 1.25rem;
  }

  .b-b-default {
    border-bottom: 1px solid #e0e0e0;
  }

  .m-b-20 {
    margin-bottom: 20px;
  }

  .p-b-5 {
    padding-bottom: 5px !important;
  }

  .card .card-block p {
    line-height: 25px;
  }

  .m-b-10 {
    margin-bottom: 10px;
  }

  .text-muted {
    color: #919aa3 !important;
  }

  .b-b-default {
    border-bottom: 1px solid #e0e0e0;
  }

  .f-w-600 {
    font-weight: 600;
  }

  .m-b-20 {
    margin-bottom: 20px;
  }

  .m-t-40 {
    margin-top: 20px;
  }

  .p-b-5 {
    padding-bottom: 5px !important;
  }

  .m-b-10 {
    margin-bottom: 10px;
  }

  .m-t-40 {
    margin-top: 20px;
  }

  .user-card-full .social-link li {
    display: inline-block;
  }

  .user-card-full .social-link li a {
    font-size: 20px;
    margin: 0 10px 0 0;
    -webkit-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
  }
</style>

<main>
  <div class="container-fluid justify-content-center align-middle py-5">
    <div class="container w-50 justify-content-center">
          <div class="card user-card-full">
            <div class="row m-l-0 m-r-0">
              <div class="col-sm-4 bg-c-lite-green user-profile">
                <div class="card-block text-center text-white">
                  <h1 class="f-w-600">Profile</h6>
                  <i
                    class="mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"
                  ></i>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="card-block">
                  <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                  <div class="row">
                    <div class="col-sm-6">
                      <p class="m-b-10 f-w-600">Name</p>
                      <h6 class="text-muted f-w-400"><div id="name"></div></h6>
                    </div>
                    <div class="col-sm-6">
                      <p class="m-b-10 f-w-600">Email</p>
                      <h6 class="text-muted f-w-400"><div id="email"></div></h6>
                    </div>
                  </div>
                  <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">
                    Role
                  </h6>
                  {{user.roles}}
                  <div class="row">
                    <div class="col-sm-6">
                      <p class="m-b-10 f-w-600"><div id="role" class="m-b-10 f-w-600"></div></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</main>

<script>
  $(function() { 
    // whatever code is here will be executed when the page loads
    $.ajax({
      type: "GET",
      url: "/landing/json",
      dataType: "json",
      success: function (data) {
        var datanya = data;
        var nameHtml = "";
        var emailHtml = "";
        var roleHtml = "";
        var item = datanya[0].fields;
        nameHtml += item.name;
        emailHtml += item.email;
        if(item.roles == "K"){
          roleHtml += "Konsumen";
        }else if(item.roles == "P"){
          roleHtml += "Pemilik";
        } else{
            roleHtml += "Investor";
          }
        document.getElementById('name').innerHTML = nameHtml;
        document.getElementById('email').innerHTML = emailHtml;
        document.getElementById('role').innerHTML = roleHtml;
      },
    });
});
</script>

{% endblock content %}

landing/templates/register.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Register</title>
{% endblock meta %} {% block content %}
<style>
  .bg-image-vertical {
    position: relative;
    overflow: hidden;
    background-repeat: no-repeat;
    background-position: right center;
    background-size: auto 100%;
  }

  @media (min-width: 500px) {
    .h-custom-2 {
      margin-top: 500px;
      height: 100%;
    }
  }
</style>

<body>
  <section class="vh-100">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6 text-black">
          <div
            class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5"
          >
            <form style="width: 23rem" method="post">
              {% csrf_token %}
              <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px">
                Register
              </h3>
              {{ form.as_p }}
              <div class="pt-1 mb-4">
                <input
                  class="w-100 btn btn-lg btn-primary"
                  type="submit"
                  value="Register"
                />
              </div>

              <p>
                Already have an account?
                <a href="{% url 'landing:login' %}" class="link-info"
                  >Login here</a
                >
              </p>
            </form>
          </div>
        </div>
        <div class="col-sm-6 px-0 d-none d-sm-block">
          <img
            src="https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1630219755/qi2qfpdn1vivt6txizxs.jpg"
            alt="Register image"
            class="w-100 vh-100"
            style="object-fit: cover; object-position: left"
          />
        </div>
      </div>
    </div>
  </section>
</body>

{% endblock content %}