auth/urls.py
from django.urls import path
from auth.views import login_user, register_user, logout_user

app_name = "auth"

urlpatterns = [
    path("login", login_user, name="login"),
    path("register", register_user, name="register"),
    path("logout", logout_user, name="logout"),
]

profileUMKM/urls.py
from django.urls import path
from profileUMKM import views

app_name = "profile-UMKM"

urlpatterns = [
    path("", views.list_profile_UMKM, name="list_profile_UMKM"),
    path("json/", views.list_profile_UMKM_json, name="list_profile_UMKM_json"),
    path("json/<int:pk>/", views.get_profile_UMKM_json, name="get_profile_UMKM_json"),
    # path("add/", views.create_profile_UMKM, name="create_profile_UMKM"),
    # path("delete/<int:pk>/", views.delete_profile_UMKM, name="delete_profile_UMKM"),
    path("add/", views.create_profile_UMKM_flutter, name="create_profile_UMKM_flutter"),
    path(
        "delete/<int:pk>/",
        views.delete_profile_UMKM_flutter,
        name="delete_profile_UMKM_flutter",
    ),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("penjualan/", include("penjualan.urls")),
    path("landing/", include("landing.urls")),
    path("berita/", include("berita.urls")),
    path("profile-umkm/", include("profileUMKM.urls")),
    path("reviewUMKM/", include("reviewUMKM.urls")),
    path("authentication/", include("authentication.urls")),
]

reviewUMKM/urls.py
from django.urls import path
from reviewUMKM import views

app_name = "reviewUMKM"

urlpatterns = [
    path("", views.home, name="index"),
    path("success", views.success, name="success"),
    path("rate/<int:id>", views.rate, name="rate"),
    path("rate_flutter/<int:idUmkm>", views.rate_flutter, name="rate_flutter"),
    path("home/", views.success, name="home"),
    path("json/", views.show_rating_json, name="show_rating_json"),
    path("<int:id>/", views.show_json_by_id, name="show_json_by_id"),
]

reviewUMKM/models.py
from django.db import models
from profileUMKM.models import ProfileUMKM
from landing.models import Profile


class Review(models.Model):
    author = models.ForeignKey(
        to=Profile, on_delete=models.CASCADE, related_name="reviews"
    )
    review_date = models.DateTimeField(auto_now_add=True)
    rate_choices = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))
    rating = models.IntegerField(choices=rate_choices)
    comment = models.TextField(max_length=2048)
    umkm = models.ForeignKey(to=ProfileUMKM, on_delete=models.CASCADE)

reviewUMKM/forms.py
from reviewUMKM.models import Review
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["rating", "comment"]

reviewUMKM/views.py
from django.shortcuts import render, redirect
from profileUMKM.models import ProfileUMKM
from .models import Review
from .forms import ReviewForm
from django.http import HttpResponse,JsonResponse
from django.core import serializers
from landing.models import Profile
from django.views.decorators.csrf import csrf_exempt


def home(request):
    user = ""
    if request.user.is_authenticated:
        user = Profile.objects.get(user=request.user)
    return render(
        request,
        "reviewUMKM/home.html",
        context={
            "user": user,
            "is_authenticated": request.user.is_authenticated,
        },
    )


def rate(request, id):
    form = ReviewForm(request.POST or None)
    if form.is_valid():
        post = ProfileUMKM.objects.get(id=id)
        author = Profile.objects.get(user=request.user)
        rating = request.POST.get("rating")
        comment = request.POST.get("comment")
        review = Review(author=author, rating=rating, comment=comment, umkm=post)
        review.save()
        return redirect("reviewUMKM:success")

    form = ReviewForm()
    context = {"form": form}
    return render(request, "reviewUMKM/rate.html", context)


@csrf_exempt
def rate_flutter(request,idUmkm):
    post = ProfileUMKM.objects.get(id=idUmkm)
    author = Profile.objects.get(user=request.user)
    rating = request.POST.get("rating")
    comment = request.POST.get("comment")
    review = Review(author=author, rating=rating, comment=comment, umkm=post)
    review.save()
    return JsonResponse({
            'status': True,
            'message': 'Review Berhasil ditambahkan!',
      
        }, status=200)



def success(request):
    return render(request, "reviewUMKM/success.html")


def show_json_by_id(request, id):
    ratingbyid = Review.objects.get(pk=id)
    return HttpResponse(
        serializers.serialize("json", [ratingbyid]), content_type="application/json"
    )


def show_rating_json(request):
    rating = Review.objects.all()
    return HttpResponse(
        serializers.serialize("json", rating), content_type="application/json"
    )

reviewUMKM/templates/reviewUMKM/detail.html
{% extends "base.html" %} {% load static %} {% block meta %}
<title>Detail Review UMKM</title>
<link
  rel="stylesheet"
  type="text/css"
  href=" {% static 'reviewUMKM/style.css' %} "
/>
{% endblock meta %} {% block content %}

<div class="header-review d-flex justify-content-between">
  <h1>Review<br />UMKM</h1>
</div>

<script>
  const getProfileUMKM = async () => {
    const response = await fetch("{% url 'profile-UMKM:get_profile_UMKM' %}");
    return await response.json();
  };

  const addReviewUMKM = ({
    pk,
    fields: { rating, comment, review_date, author },
  }) => {
    const id = pk;

    let photoTag = "";

    const reviewUMKM =
      `
      <div class="card flex-row flex-wrap">
        <div class="card-header border-0">
            ` +
      photoTag +
      `
        </div>
        <div class="card-block mx-6">
            <h4 class="card-title">${nama}</h4>
            <p class="card-text">${pemilik}</p>
        </div>
    </div>
    `;

    document.getElementById("profil-umkm").innerHTML += profileUMKM;
  };
</script>

{% endblock content %}

reviewUMKM/templates/reviewUMKM/home.html
{% extends "base.html" %} {% load static %} {% block meta %}
<title>Review UMKM</title>
<link
  rel="stylesheet"
  type="text/css"
  href=" {% static 'reviewUMKM/style.css' %} "
/>
{% endblock meta %} {% block content %}

<div class="header-review d-flex justify-content-between">
  <h1>Review<br />UMKM</h1>
</div>

<div id="profil-umkm"></div>

<script>
  const getProfilesUMKM = async () => {
    const response = await fetch(
      "{% url 'profile-UMKM:list_profile_UMKM_json' %}"
    );
    return await response.json();
  };

  const refreshProfilesUMKM = async () => {
    const profilesUMKM = await getProfilesUMKM();
    profilesUMKM.forEach((profileUMKM) => {
      addCardProfileUMKM(profileUMKM);
    });
  };

  const addCardProfileUMKM = ({ pk, fields: { nama, pemilik, foto } }) => {
    const id = pk;

    let photoTag = "";

    if (foto) {
      photoTag = `
        <div class="position-relative rounded-circle overflow-hidden mx-auto custom-circle-image">
          <img src="${foto}" alt="Avatar" class="w-100 h-100">
          <svg>
            <use 
              href="{% static "reviewUMKM/star.svg" %}#my_image"
            >
            </use>
          </svg>
        </div>
      `;
    }

    var sensorID = "href='{% url 'reviewUMKM:rate' 12345 %}'";
    var url_mask = sensorID.replace("12345", id);
    console.log(url_mask)
    const profileUMKM =
      `
      <div id="card-${id}" class="card flex-row flex-wrap card-review">
        <div class="card-header border-0 card-image-stars">
            ` +
      photoTag +
      `
        </div>
        <div class="card-block mx-6 card-body">
            <h4 class="card-title">${nama}</h4>
            <p class="card-text">${pemilik}</p>
            {% if is_authenticated and user.roles == "K" %}
            <a `+url_mask+`>
              <button type="button" class="btn btn-secondary" style="background-color: #395144">Rate Now</button>
            </a>
            {% endif %}
        </div>
    </div>
    `;

    document.getElementById("profil-umkm").innerHTML += profileUMKM;
  };

  refreshProfilesUMKM();
</script>

<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

{% endblock content %}

reviewUMKM/templates/reviewUMKM/rate.html
{% extends "base.html" %} {% load static %} {% block meta %}
<title>Review UMKM</title>
<link
  rel="stylesheet"
  type="text/css"
  href=" {% static 'reviewUMKM/style.css' %} "
/>
{% endblock meta %} 
{% block content %}
<div>
  <form method="POST" id="rate">
    {% csrf_token %} {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Rate Now</button>
  </form>
</div>
{% endblock content %}

reviewUMKM/templates/reviewUMKM/success.html
{% extends "base.html"%} {% block content %}
<h1 style="margin-top: 20%;">Thanks for the review and rating this UMKM!</h1>
<a
  class="btn btn-danger"
  style="color: white;"
  href="{% url 'reviewUMKM:index' %}"
  >close</a
>

{% endblock content %}